cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala
language: java

branches:
  - /.*/

scala:
  - 2.12.7

jdk:
  - openjdk8

script:
  - mvn clean install
